export const HOME_FETCH_QUESTIONS_BEGIN = 'HOME_FETCH_QUESTIONS_BEGIN';
export const HOME_FETCH_QUESTIONS_SUCCESS = 'HOME_FETCH_QUESTIONS_SUCCESS';
export const HOME_FETCH_QUESTIONS_FAILURE = 'HOME_FETCH_QUESTIONS_FAILURE';
export const HOME_FETCH_QUESTIONS_DISMISS_ERROR = 'HOME_FETCH_QUESTIONS_DISMISS_ERROR';
export const HOME_SET_ANSWERS = 'HOME_SET_ANSWERS';
